"use client";
import Image from "next/image";
import Link from "next/link";
import { HugeiconsIcon } from "@hugeicons/react";
import type { IconSvgElement } from "@hugeicons/react";
import { Activity01Icon, ArrowDown01Icon, ArrowRight01Icon, Building01Icon, Cancel01Icon, CheckmarkCircle02Icon, ContainerTruck01Icon, Delete02Icon, Invoice01Icon, Package01Icon, PlusSignIcon, Search01Icon } from "@hugeicons/core-free-icons";
import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { client, queryClient } from "@/utils/orpc";
import { formatGhs } from "@/lib/sample-catalog";
import { AdminPagination, paginateItems } from "@/components/admin/admin-pagination";
const IK=["admin-inventory"],AK=["admin-inventory-adjustments"],SK=["admin-inventory-suppliers"],PK=["admin-inventory-purchase-orders"];
type V=Awaited<ReturnType<typeof client.listInventory>>[number];type S=Awaited<ReturnType<typeof client.listInventorySuppliers>>[number];type O=Awaited<ReturnType<typeof client.listInventoryPurchaseOrders>>[number];
type DL={key:string;variantId:string;qty:string;cost:string};type SD={name:string;contact:string;phone:string;email:string;location:string;leadTimeDays:number;notes:string;active:boolean};
const blank:SD={name:"",contact:"",phone:"",email:"",location:"",leadTimeDays:7,notes:"",active:true};
const useInventoryQuery=()=>useQuery({queryKey:IK,queryFn:()=>client.listInventory(),staleTime:15000,refetchInterval:30000}),useSupplierQuery=()=>useQuery({queryKey:SK,queryFn:()=>client.listInventorySuppliers(),staleTime:15000,refetchInterval:30000}),usePurchaseOrdersQuery=()=>useQuery({queryKey:PK,queryFn:()=>client.listInventoryPurchaseOrders(),staleTime:15000,refetchInterval:30000});
const refresh=()=>Promise.all([IK,AK,SK,PK].map(queryKey=>queryClient.invalidateQueries({queryKey})));
function I({icon}:{icon:IconSvgElement}){return <HugeiconsIcon icon={icon} aria-hidden="true"/>}
function Photo({src}:{src:string}){return <span className="inventory-photo"><Image src={src||"/images/product-placeholder.svg"} alt="" fill sizes="96px"/></span>}
function Head({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="inventory-heading"><div><p className="admin-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Badge({value}:{value:string}){const tone=/out|cancel/i.test(value)?"bad":/low|partial|draft|ordered|inactive/i.test(value)?"warm":/received|active|in stock/i.test(value)?"good":"neutral";return <span className={"inventory-badge inventory-badge--"+tone}><i/>{value}</span>}
function Empty({icon=Package01Icon,title,description,action}:{icon?:IconSvgElement;title:string;description:string;action?:React.ReactNode}){return <div className="inventory-empty-state"><span><I icon={icon}/></span><h2>{title}</h2><p>{description}</p>{action}</div>}
function Loading(){return <div className="inventory-skeleton" role="status" aria-label="Loading">{[1,2,3,4,5].map(n=><span key={n}/>)}</div>}
function ErrorBox({retry}:{retry:()=>void}){return <div className="inventory-error-state" role="alert"><strong>Couldn’t load this information.</strong><span>Check your connection and try again.</span><button className="admin-secondary-button" onClick={retry}>Try again</button></div>}
function vl(v:V){return v.colour+" · "+(v.size==="One size"?"One size":"EU "+v.size)}
function sl(v:string){return ({draft:"Draft",ordered:"Ordered",partially_received:"Partially received",received:"Received",cancelled:"Cancelled"} as Record<string,string>)[v]||v}
function date(v:Date|string|null){if(!v)return "Not set";const d=new Date(v);return isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("en-GH",{dateStyle:"medium"}).format(d)}

export function InventoryOverviewWorkspace(){
 const q=useInventoryQuery();
 if(q.isLoading)return <div className="inventory-workspace"><Head eyebrow="INVENTORY · ACCRA" title="Stock overview" description="Shared stock by product option."/><Loading/></div>;
 if(q.isError)return <div className="inventory-workspace"><Head eyebrow="INVENTORY · ACCRA" title="Stock overview" description="Shared stock by product option."/><ErrorBox retry={()=>void q.refetch()}/></div>;
 return <InventoryOverviewLoaded vs={q.data||[]}/>;
}

function InventoryOverviewLoaded({vs}:{vs:V[]}){
 const[search,ss]=useState(""),[level,slev]=useState("All stock"),[category,sc]=useState("All categories"),[page,sp]=useState(1);
 const threshold=useMutation({mutationFn:(input:{variantId:string;threshold:number})=>client.setInventoryThreshold(input),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:IK});toast.success("Reorder point saved")},onError:e=>toast.error(e.message)});
 const filtered=useMemo(()=>vs.filter(v=>(level==="All stock"||(level==="Low stock"&&v.onHand>0&&v.onHand<=v.lowStockThreshold)||(level==="Out of stock"&&!v.onHand))&&(category==="All categories"||v.category===category)&&(v.productName+v.sku+v.colour+v.size).toLowerCase().includes(search.toLowerCase())),[vs,level,category,search]),shown=paginateItems(filtered,page,25);
 return <div className="inventory-workspace"><Head eyebrow="INVENTORY · ACCRA STORE" title="Stock overview" description="Check stock by product option and spot items that need attention." action={<Link className="admin-primary-button" href="/admin/inventory/adjustments"><I icon={Activity01Icon}/> Adjust stock</Link>}/>
 <div className="inventory-summary"><div><span>Units on hand</span><strong>{vs.reduce((n,v)=>n+v.onHand,0)}</strong><small>Across {vs.length} variants</small></div><div><span>Low stock</span><strong>{vs.filter(v=>v.onHand>0&&v.onHand<=v.lowStockThreshold).length}</strong><small>At or below reorder point</small></div><div><span>Out of stock</span><strong>{vs.filter(v=>!v.onHand).length}</strong><small>Unavailable variants</small></div></div>
 {!vs.length?<Empty title="Your inventory starts with a product variant" description="Add products with colour or size options. Their real stock levels appear here automatically." action={<Link className="admin-primary-button" href="/admin/catalogue/products">Go to products</Link>}/>:<>
 <div className="inventory-toolbar"><label className="inventory-search"><I icon={Search01Icon}/><input value={search} onChange={e=>{ss(e.target.value);sp(1)}} placeholder="Search product, option, SKU"/></label><label className="inventory-select"><span>Stock level</span><select value={level} onChange={e=>slev(e.target.value)}><option>All stock</option><option>Low stock</option><option>Out of stock</option></select><I icon={ArrowDown01Icon}/></label><label className="inventory-select"><span>Category</span><select value={category} onChange={e=>sc(e.target.value)}><option>All categories</option>{Array.from(new Set(vs.map(v=>v.category))).map(c=><option key={c}>{c}</option>)}</select><I icon={ArrowDown01Icon}/></label><span className="inventory-result-count">{filtered.length} variants</span></div>
 {!filtered.length?<Empty title="No variants match these filters" description="Try a different search or clear filters." action={<button className="admin-secondary-button" onClick={()=>{ss("");slev("All stock");sc("All categories")}}>Clear filters</button>}/>:<><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Product & option</th><th>SKU</th><th>Location</th><th>On hand</th><th>Reorder point</th><th>Status</th></tr></thead><tbody>{shown.map(v=><tr key={v.id}><td><div className="inventory-product-cell"><Photo src={v.productImage}/><span><strong>{v.productName}</strong><small>{vl(v)}</small></span></div></td><td>{v.sku}</td><td>{v.location}</td><td>{v.onHand}</td><td><input className="inventory-threshold-input" type="number" min="0" defaultValue={v.lowStockThreshold} key={v.id+v.lowStockThreshold} onBlur={e=>{const n=Number(e.currentTarget.value);if(Number.isInteger(n)&&n>=0&&n!==v.lowStockThreshold)threshold.mutate({variantId:v.id,threshold:n})}} aria-label={"Reorder point "+v.productName}/></td><td><Badge value={!v.onHand?"Out of stock":v.onHand<=v.lowStockThreshold?"Low stock":"In stock"}/></td></tr>)}</tbody></table></div><div className="inventory-mobile-list">{shown.map(v=><article className="inventory-mobile-card" key={"m"+v.id}><div className="inventory-product-cell"><Photo src={v.productImage}/><span><strong>{v.productName}</strong><small>{vl(v)} · {v.sku}</small></span></div><div className="inventory-mobile-card__stats"><span>On hand <strong>{v.onHand}</strong></span></div><div className="inventory-mobile-card__footer"><Badge value={!v.onHand?"Out of stock":v.onHand<=v.lowStockThreshold?"Low stock":"In stock"}/><label>Reorder point<input type="number" min="0" defaultValue={v.lowStockThreshold} key={"m"+v.id+v.lowStockThreshold} onBlur={e=>{const n=Number(e.currentTarget.value);if(Number.isInteger(n)&&n>=0&&n!==v.lowStockThreshold)threshold.mutate({variantId:v.id,threshold:n})}}/></label></div></article>)}</div><AdminPagination total={filtered.length} page={page} pageSize={25} onPageChange={sp} label="stock variants"/></>}
 </>}
 <p className="inventory-footnote">On-hand counts and reorder points are shared with product availability. Reservation tracking is not enabled yet.</p></div>;
}

export function StockAdjustmentsWorkspace(){
 const vq=useInventoryQuery(),aq=useQuery({queryKey:AK,queryFn:()=>client.listStockAdjustments(),staleTime:15000,refetchInterval:30000}),vs=vq.data||[],history=aq.data||[];
 const[id,sid]=useState(""),[action,sa]=useState<"add"|"remove"|"set">("add"),[qty,sq]=useState(""),[reason,sr]=useState("Cycle count correction"),[note,sn]=useState(""),[search,ss]=useState(""),[page,sp]=useState(1);
 const selected=vs.find(v=>v.id===id),n=Number(qty),next=selected?(action==="add"?selected.onHand+n:action==="remove"?selected.onHand-n:n):0;
 const save=useMutation({mutationFn:(input:{variantId:string;action:"add"|"remove"|"set";quantity:number;reason:string;note?:string})=>client.createStockAdjustment(input),onSuccess:async()=>{await refresh();sq("");sn("");toast.success("Stock adjustment saved")},onError:e=>toast.error(e.message)});
 if(vq.isLoading||aq.isLoading)return <div className="inventory-workspace"><Head eyebrow="INVENTORY · CONTROL" title="Stock adjustments" description="Record counts and corrections."/><Loading/></div>;
 if(vq.isError||aq.isError)return <div className="inventory-workspace"><Head eyebrow="INVENTORY · CONTROL" title="Stock adjustments" description="Record counts and corrections."/><ErrorBox retry={()=>{void vq.refetch();void aq.refetch()}}/></div>;
 const filtered=history.filter(r=>(r.reference+r.productName+r.sku+r.reason).toLowerCase().includes(search.toLowerCase())),shown=paginateItems(filtered,page,25);
 return <div className="inventory-workspace"><Head eyebrow="INVENTORY · STOCK CONTROL" title="Stock adjustments" description="Record a count, damaged item, or correction with a clear reason." action={<Link className="admin-secondary-button" href="/admin/inventory">Back to stock</Link>}/><div className="adjustment-layout"><section className="adjustment-form-card"><div className="inventory-section-title"><span className="inventory-step-number">01</span><div><h2>New adjustment</h2><p>Updates shared stock and appends an audit record.</p></div></div>
 {!vs.length?<Empty title="No variants to adjust yet" description="Add a product with colour or size options first." action={<Link className="admin-secondary-button" href="/admin/catalogue/products">Go to products</Link>}/>:<>
 <label className="inventory-field">Product variant<select value={id} onChange={e=>sid(e.target.value)}><option value="">Select product, colour, size</option>{vs.map(v=><option key={v.id} value={v.id}>{v.productName} · {vl(v)} · {v.sku}</option>)}</select></label>
 <div className="inventory-form-grid"><label className="inventory-field">Adjustment type<select value={action} onChange={e=>sa(e.target.value as typeof action)}><option value="add">Add stock</option><option value="remove">Remove stock</option><option value="set">Set exact count</option></select></label><label className="inventory-field">{action==="set"?"New on-hand quantity":"Units to adjust"}<input type="number" min="0" step="1" value={qty} onChange={e=>sq(e.target.value)}/></label><label className="inventory-field inventory-field--wide">Reason<select value={reason} onChange={e=>sr(e.target.value)}><option>Cycle count correction</option><option>Damaged item</option><option>Found stock</option><option>Opening balance</option><option>Other</option></select></label><label className="inventory-field inventory-field--wide">Note <small>Optional team context</small><textarea rows={3} value={note} onChange={e=>sn(e.target.value)}/></label></div>{selected&&<div className="adjustment-preview"><span>Current on hand<strong>{selected.onHand}</strong></span><span>After adjustment<strong>{qty?next:"—"}</strong></span></div>}<button className="admin-primary-button" disabled={!selected||!Number.isInteger(n)||n<0||(action!=="set"&&!n)||next<0||next===selected.onHand||save.isPending} onClick={()=>save.mutate({variantId:id,action,quantity:n,reason,note})}>{save.isPending?"Saving…":"Save adjustment"} <I icon={CheckmarkCircle02Icon}/></button></>}
 </section><aside className="adjustment-guidance"><span><I icon={Activity01Icon}/></span><h2>Every change has a reason.</h2><p>Previous and new counts, SKU, staff member, and time stay together.</p><div><strong>Stock rules</strong><ul><li>Tracked by colour and size.</li><li>Stock cannot fall below zero.</li><li>Supplier receipts link to orders.</li></ul></div><Link href="/admin/purchasing/orders">Receive supplier stock <I icon={ArrowRight01Icon}/></Link></aside></div>
 <section className="inventory-history"><div className="inventory-section-title"><div><p className="admin-eyebrow">AUDIT TRAIL</p><h2>Recent adjustments</h2></div><label className="inventory-search inventory-search--compact"><I icon={Search01Icon}/><input value={search} onChange={e=>{ss(e.target.value);sp(1)}} placeholder="Search adjustments"/></label></div>{!filtered.length?<Empty title={history.length?"No matching adjustments":"No stock changes recorded yet"} description={history.length?"Try another query.":"Adjustments and receipts will appear here."}/>:<><div className="inventory-table-wrap"><table className="inventory-table inventory-adjustment-table"><thead><tr><th>Reference & date</th><th>Product variant</th><th>Change</th><th>Previous → new</th><th>Reason</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><strong>{r.reference}</strong><small>{new Intl.DateTimeFormat("en-GH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(r.createdAt))}</small></td><td><strong>{r.productName}</strong><small>{r.variantLabel} · {r.sku}</small></td><td>{r.change>0?"+":""}{r.change}</td><td>{r.previous} → {r.next}</td><td><strong>{r.reason}</strong>{r.note&&<small>{r.note}</small>}</td></tr>)}</tbody></table></div><AdminPagination total={filtered.length} page={page} pageSize={25} onPageChange={sp} label="adjustments"/></>}</section></div>;
}

export function PurchaseOrdersWorkspace(){
 const vq=useInventoryQuery(),sq=useSupplierQuery(),pq=usePurchaseOrdersQuery(),vs=vq.data||[],suppliers=sq.data||[],orders=pq.data||[],active=suppliers.filter(s=>s.active);
 const[filter,sf]=useState("All orders"),[search,ss]=useState(""),[page,sp]=useState(1),[open,so]=useState(false),[editId,se]=useState<string|null>(null),[selectedId,si]=useState<string|null>(null),[receiveId,sri]=useState<string|null>(null),[receiving,sr]=useState<Record<string,string>>({}),[supplierId,ssid]=useState(""),[expected,sex]=useState(""),[supplierRef,ssr]=useState(""),[draftNote,sdn]=useState(""),[note,sn]=useState(""),[lines,slines]=useState<DL[]>([]),[error,serr]=useState("");
 const selected=orders.find(o=>o.id===selectedId),rec=orders.find(o=>o.id===receiveId);
 const save=useMutation({mutationFn:(input:{id?:string;supplierId:string;expectedAt?:string;supplierReference?:string;note?:string;status:"draft"|"ordered";lines:{variantId:string;quantityOrdered:number;unitCostPesewas:number}[]})=>client.saveInventoryPurchaseOrder(input),onSuccess:async o=>{await refresh();so(false);se(null);si(o?.id||null);toast.success("Purchase order saved")},onError:e=>serr(e.message)});
 const status=useMutation({mutationFn:(input:{id:string;status:"ordered"|"cancelled"})=>client.updateInventoryPurchaseOrderStatus(input),onSuccess:async o=>{await refresh();si(o?.id||null)},onError:e=>toast.error(e.message)});
 const receipt=useMutation({mutationFn:(input:{id:string;receiptId:string;note?:string;lines:{lineId:string;quantity:number}[]})=>client.receiveInventoryPurchaseOrder(input),onSuccess:async o=>{await refresh();sri(null);si(o?.id||null);toast.success("Receipt saved")},onError:e=>serr(e.message)});
 const filtered=orders.filter(o=>(filter==="All orders"||sl(o.status)===filter)&&(o.reference+o.supplierName+o.supplierReference).toLowerCase().includes(search.toLowerCase())),shown=paginateItems(filtered,page,25);
 function create(){se(null);ssid(active[0]?.id||"");sex("");ssr("");sdn("");slines([]);serr("");so(true)}
 function edit(o:O){se(o.id);ssid(o.supplierId);sex(o.expectedAt||"");ssr(o.supplierReference);sdn(o.note);slines(o.lines.map(l=>({key:l.id,variantId:l.variantId,qty:String(l.quantityOrdered),cost:String(l.unitCostGhs)})));si(null);so(true)}
 function submit(state:"draft"|"ordered"){if(!supplierId||!lines.length||new Set(lines.map(l=>l.variantId)).size!==lines.length||lines.some(l=>!Number.isInteger(Number(l.qty))||Number(l.qty)<1||!Number.isFinite(Number(l.cost))||Number(l.cost)<0)){serr("Choose a supplier and enter valid unique product lines.");return}if(expected&&expected<new Date().toISOString().slice(0,10)){serr("Expected date cannot be in the past.");return}save.mutate({...(editId?{id:editId}:{}),supplierId,expectedAt:expected,supplierReference:supplierRef,note:draftNote,status:state,lines:lines.map(l=>({variantId:l.variantId,quantityOrdered:Number(l.qty),unitCostPesewas:Math.round(Number(l.cost)*100)}))})}
 function beginReceive(o:O){sri(o.id);si(null);serr("");sr(Object.fromEntries(o.lines.map(l=>[l.id,String(l.quantityOrdered-l.quantityReceived)])))}
 function doReceive(){if(!rec)return;const received=rec.lines.flatMap(l=>{const n=Number(receiving[l.id]||0);return Number.isInteger(n)&&n>0&&n<=l.quantityOrdered-l.quantityReceived?[{lineId:l.id,quantity:n}]:[]});if(!received.length){serr("Enter at least one valid quantity received.");return}receipt.mutate({id:rec.id,receiptId:crypto.randomUUID(),note,lines:received})}
 const loading=vq.isLoading||sq.isLoading||pq.isLoading,failed=vq.isError||sq.isError||pq.isError;
 return <div className="inventory-workspace">
 <Head eyebrow="PURCHASING · STOCK IN" title="Purchase orders" description="Create supplier orders, track delivery, and receive stock." action={<button className="admin-primary-button" disabled={!active.length} onClick={create}><I icon={PlusSignIcon}/> New purchase order</button>}/>
 {loading&&<Loading/>}
 {failed&&<ErrorBox retry={()=>{void vq.refetch();void sq.refetch();void pq.refetch()}}/>}
 {!loading&&!failed&&<>
 <div className="inventory-summary inventory-summary--purchasing"><div><span>Open orders</span><strong>{orders.filter(o=>["ordered","partially_received"].includes(o.status)).length}</strong><small>Awaiting or part received</small></div><div><span>Suppliers</span><strong>{active.length}</strong><small>Active suppliers</small></div><div><span>Items due</span><strong>{orders.filter(o=>["ordered","partially_received"].includes(o.status)).reduce((n,o)=>n+o.lines.reduce((a,l)=>a+l.quantityOrdered-l.quantityReceived,0),0)}</strong><small>Still due</small></div></div>
 {!active.length&&<Empty icon={Building01Icon} title="Add a supplier before ordering" description="Each order needs a supplier record." action={<Link className="admin-primary-button" href="/admin/purchasing/suppliers">Add supplier</Link>}/>}
 <div className="inventory-toolbar inventory-toolbar--list"><label className="inventory-search"><I icon={Search01Icon}/><input value={search} onChange={e=>{ss(e.target.value);sp(1)}} placeholder="Search order or supplier"/></label><span className="inventory-result-count">{filtered.length} orders</span></div>
 <div className="inventory-filter-tabs" role="tablist" aria-label="Purchase order status">{["All orders","Draft","Ordered","Partially received","Received","Cancelled"].map(s=><button key={s} role="tab" aria-selected={filter===s} onClick={()=>sf(s)}>{s}<span>{s==="All orders"?orders.length:orders.filter(o=>sl(o.status)===s).length}</span></button>)}</div>
 {!filtered.length?<Empty title={orders.length?"No orders match this view":"No purchase orders yet"} description={orders.length?"Try another status or search term.":active.length?"Create the first supplier order.":"Add a supplier first."} action={orders.length?<button className="admin-secondary-button" onClick={()=>{sf("All orders");ss("")}}>Clear filters</button>:active.length?<button className="admin-primary-button" onClick={create}>Create purchase order</button>:null}/>:<>
 <div className="inventory-table-wrap"><table className="inventory-table purchase-order-table"><thead><tr><th>Order</th><th>Supplier</th><th>Created</th><th>Expected</th><th>Due</th><th>Value</th><th>Status</th><th/></tr></thead><tbody>{shown.map(o=><tr key={o.id} onClick={()=>si(o.id)}><td><button className="inventory-link-button" onClick={e=>{e.stopPropagation();si(o.id)}}>{o.reference}</button></td><td>{o.supplierName}</td><td>{date(o.createdAt)}</td><td>{date(o.expectedAt)}</td><td>{o.lines.reduce((n,l)=>n+l.quantityOrdered-l.quantityReceived,0)}</td><td>{formatGhs(o.lines.reduce((n,l)=>n+l.quantityOrdered*l.unitCostGhs,0))}</td><td><Badge value={sl(o.status)}/></td><td><button className="inventory-icon-button" aria-label={"View "+o.reference} onClick={e=>{e.stopPropagation();si(o.id)}}><I icon={ArrowRight01Icon}/></button></td></tr>)}</tbody></table></div>
 <AdminPagination total={filtered.length} page={page} pageSize={25} onPageChange={sp} label="orders"/>
 </>}
 </>}
 {selected&&<OrderDetail order={selected} close={()=>si(null)} edit={()=>edit(selected)} receive={()=>beginReceive(selected)} status={s=>status.mutate({id:selected.id,status:s})} pending={status.isPending}/>}
 {open&&<div className="inventory-modal-backdrop"><section className="inventory-modal inventory-create-po" role="dialog" aria-modal="true"><h2>{editId?"Edit draft":"New purchase order"}</h2><div className="inventory-form-grid"><label className="inventory-field">Supplier<select value={supplierId} onChange={e=>ssid(e.target.value)}><option value="">Select supplier</option>{active.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="inventory-field">Expected delivery<input type="date" value={expected} onChange={e=>sex(e.target.value)}/></label><label className="inventory-field">Supplier reference<input value={supplierRef} onChange={e=>ssr(e.target.value)}/></label></div>
 <button className="admin-secondary-button" onClick={()=>{const v=vs.find(x=>!lines.some(l=>l.variantId===x.id));if(v)slines(a=>[...a,{key:crypto.randomUUID(),variantId:v.id,qty:"1",cost:"0"}])}}>Add product line</button>
 {lines.map(l=><div className="po-draft-line" key={l.key}><label className="inventory-field">Variant<select value={l.variantId} onChange={e=>slines(a=>a.map(x=>x.key===l.key?{...x,variantId:e.target.value}:x))}>{vs.map(v=><option key={v.id} value={v.id}>{v.productName} · {v.colour} · {v.size}</option>)}</select></label><label className="inventory-field">Qty<input type="number" min="1" value={l.qty} onChange={e=>slines(a=>a.map(x=>x.key===l.key?{...x,qty:e.target.value}:x))}/></label><label className="inventory-field">Unit cost GHS<input type="number" min="0" step="0.01" value={l.cost} onChange={e=>slines(a=>a.map(x=>x.key===l.key?{...x,cost:e.target.value}:x))}/></label><button onClick={()=>slines(a=>a.filter(x=>x.key!==l.key))}><I icon={Delete02Icon}/></button></div>)}
 <label className="inventory-field">Internal note<textarea value={draftNote} onChange={e=>sdn(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}
 <div className="inventory-modal__actions"><button className="admin-secondary-button" onClick={()=>submit("draft")} disabled={!lines.length||save.isPending}>Save draft</button><button className="admin-primary-button" onClick={()=>submit("ordered")} disabled={!lines.length||save.isPending}>Place order</button><button className="inventory-icon-button" onClick={()=>so(false)} aria-label="Close"><I icon={Cancel01Icon}/></button></div></section></div>}
 {rec&&<div className="inventory-modal-backdrop"><section className="inventory-modal inventory-receive-modal" role="dialog" aria-modal="true"><h2>Receive {rec.reference}</h2>{rec.lines.map(l=><label className="receive-line" key={l.id}><span>{l.productName} · {l.variantLabel} · {l.quantityOrdered-l.quantityReceived} due</span><input type="number" min="0" max={l.quantityOrdered-l.quantityReceived} value={receiving[l.id]||"0"} onChange={e=>sr(a=>({...a,[l.id]:e.target.value}))}/></label>)}<label className="inventory-field">Receipt note<textarea value={note} onChange={e=>sn(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="admin-primary-button" onClick={doReceive} disabled={receipt.isPending}>{receipt.isPending?"Saving receipt…":"Confirm receipt"}</button><button className="admin-secondary-button" onClick={()=>sri(null)}>Cancel</button></section></div>}
 </div>;
}
function OrderDetail({order,close,edit,receive,status,pending}:{order:O;close:()=>void;edit:()=>void;receive:()=>void;status:(s:"ordered"|"cancelled")=>void;pending:boolean}){
 const[confirm,sc]=useState(false),total=order.lines.reduce((n,l)=>n+l.quantityOrdered*l.unitCostGhs,0);
 return <div className="inventory-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="inventory-modal" role="dialog" aria-modal="true"><div className="inventory-modal__heading"><div><p className="admin-eyebrow">PURCHASE ORDER · {date(order.createdAt)}</p><h2>{order.reference}</h2></div><button className="inventory-icon-button" onClick={close}><I icon={Cancel01Icon}/></button></div><div className="po-detail-overview"><div><span>Supplier</span><strong>{order.supplierName}</strong></div><div><span>Status</span><Badge value={sl(order.status)}/></div><div><span>Expected</span><strong>{date(order.expectedAt)}</strong></div><div><span>Order value</span><strong>{formatGhs(total)}</strong></div></div><div className="po-line-list">{order.lines.map(l=><article className="po-line-card" key={l.id}><Photo src="/images/product-placeholder.svg"/><div><strong>{l.productName}</strong><small>{l.variantLabel} · {l.sku}</small><small>Received {l.quantityReceived} of {l.quantityOrdered}</small></div><strong>{formatGhs(l.quantityOrdered*l.unitCostGhs)}</strong></article>)}</div>{order.note&&<p>{order.note}</p>}{confirm&&<p className="inventory-form-error">Cancel this order? It will no longer accept receipts. <button onClick={()=>status("cancelled")}>Confirm cancel</button></p>}<div className="inventory-modal__actions">{order.status==="draft"&&<><button className="admin-secondary-button" onClick={edit}>Edit draft</button><button className="admin-primary-button" disabled={pending} onClick={()=>status("ordered")}>Mark ordered</button></>}{["ordered","partially_received"].includes(order.status)&&<button className="admin-primary-button" onClick={receive}><I icon={ContainerTruck01Icon}/> Receive delivery</button>}{!["received","cancelled"].includes(order.status)&&!confirm&&<button className="inventory-danger-action" onClick={()=>sc(true)}>Cancel order</button>}</div></section></div>
}

export function SuppliersWorkspace(){
 const sq=useSupplierQuery(),pq=usePurchaseOrdersQuery(),suppliers=sq.data||[],orders=pq.data||[];
 const[search,ss]=useState(""),[inactive,si]=useState(false),[page,sp]=useState(1),[open,so]=useState(false),[editing,se]=useState<string|null>(null),[draft,sd]=useState<SD>(blank);
 const save=useMutation({mutationFn:(input:{id?:string;name:string;contact?:string;phone:string;email?:string;location?:string;leadTimeDays?:number;notes?:string;active:boolean})=>client.saveInventorySupplier(input),onSuccess:async()=>{await refresh();so(false);toast.success("Supplier saved")},onError:e=>toast.error(e.message)});
 const filtered=suppliers.filter(s=>(inactive||s.active)&&(s.name+s.contact+s.phone+s.location).toLowerCase().includes(search.toLowerCase())),shown=paginateItems(filtered,page,25);
 function edit(s:S){se(s.id);sd({name:s.name,contact:s.contact,phone:s.phone,email:s.email,location:s.location,leadTimeDays:s.leadTimeDays,notes:s.notes,active:s.active});so(true)}
 const load=sq.isLoading||pq.isLoading,fail=sq.isError||pq.isError;
 return <div className="inventory-workspace"><Head eyebrow="PURCHASING · PARTNERS" title="Suppliers" description="Maintain supplier contacts, lead times, and order history." action={<button className="admin-primary-button" onClick={()=>{se(null);sd(blank);so(true)}}><I icon={PlusSignIcon}/> Add supplier</button>}/>{load?<Loading/>:fail?<ErrorBox retry={()=>{void sq.refetch();void pq.refetch()}}/>:<>
 <div className="inventory-toolbar inventory-toolbar--list"><label className="inventory-search"><I icon={Search01Icon}/><input value={search} onChange={e=>ss(e.target.value)} placeholder="Search suppliers"/></label><label className="inventory-checkbox-filter"><input type="checkbox" checked={inactive} onChange={e=>si(e.target.checked)}/> Include inactive</label><span className="inventory-result-count">{filtered.length} suppliers</span></div>
 {!filtered.length?<Empty icon={Building01Icon} title={suppliers.length?"No suppliers match":"Add your first supplier"} description={suppliers.length?"Try a different search.":"Supplier details are reused on purchase orders."} action={<button className="admin-primary-button" onClick={()=>{se(null);sd(blank);so(true)}}>Add supplier <I icon={PlusSignIcon}/></button>}/>:<div className="supplier-card-grid">{shown.map(s=><article className="supplier-card" key={s.id}><div className="supplier-card__head"><span className="supplier-icon"><I icon={Building01Icon}/></span><Badge value={s.active?"Active":"Inactive"}/><button className="inventory-icon-button" onClick={()=>edit(s)}><I icon={ArrowRight01Icon}/></button></div><h2>{s.name}</h2><p className="supplier-location">{s.location||"Location not set"}</p><div className="supplier-details"><span>Contact<strong>{s.contact||"Not provided"}</strong></span><span>Phone<strong>{s.phone}</strong></span><span>Email<strong>{s.email||"Not provided"}</strong></span><span>Lead time<strong>{s.leadTimeDays} days</strong></span></div><p className="supplier-notes">{s.notes||"No notes."}</p><div className="supplier-card__footer"><span><I icon={Invoice01Icon}/> {orders.filter(o=>o.supplierId===s.id).length} orders</span><button className="catalogue-text-action" onClick={()=>save.mutate({...s,id:s.id,active:!s.active})}>{s.active?"Deactivate":"Activate"}</button></div></article>)}</div>}
 {filtered.length>0&&<AdminPagination total={filtered.length} page={page} pageSize={25} onPageChange={sp} label="suppliers"/>}</>}
 {open&&<div className="inventory-modal-backdrop"><section className="inventory-modal supplier-modal" role="dialog" aria-modal="true"><div className="inventory-modal__heading"><div><p className="admin-eyebrow">SUPPLIER PROFILE</p><h2>{editing?"Edit supplier":"Add supplier"}</h2></div><button className="inventory-icon-button" onClick={()=>so(false)}><I icon={Cancel01Icon}/></button></div><div className="inventory-form-grid"><label className="inventory-field inventory-field--wide">Business name<input value={draft.name} onChange={e=>sd({...draft,name:e.target.value})}/></label><label className="inventory-field">Contact<input value={draft.contact} onChange={e=>sd({...draft,contact:e.target.value})}/></label><label className="inventory-field">Phone<input value={draft.phone} onChange={e=>sd({...draft,phone:e.target.value})}/></label><label className="inventory-field">Email<input type="email" value={draft.email} onChange={e=>sd({...draft,email:e.target.value})}/></label><label className="inventory-field">Location<input value={draft.location} onChange={e=>sd({...draft,location:e.target.value})}/></label><label className="inventory-field">Lead time days<input type="number" min="0" value={draft.leadTimeDays} onChange={e=>sd({...draft,leadTimeDays:Number(e.target.value)||0})}/></label><label className="inventory-field inventory-field--wide">Notes<textarea value={draft.notes} onChange={e=>sd({...draft,notes:e.target.value})}/></label></div><label className="inventory-checkbox-filter"><input type="checkbox" checked={draft.active} onChange={e=>sd({...draft,active:e.target.checked})}/> Active for new orders</label><div className="inventory-modal__actions"><button className="admin-secondary-button" onClick={()=>so(false)}>Cancel</button><button className="admin-primary-button" disabled={!draft.name.trim()||!draft.phone.trim()||save.isPending} onClick={()=>save.mutate({...draft,...(editing?{id:editing}:{})})}>{save.isPending?"Saving…":"Save supplier"} <I icon={CheckmarkCircle02Icon}/></button></div></section></div>}
 </div>
}
