// Preview locations; move to admin-managed settings when delivery areas are configurable.
// Names are drawn from public ECG community listings and Local Government Service
// district profiles. This starter list is not an official delivery boundary map.
const accraAreaGroups = [
  {
    group: "Central Accra",
    places: [
      "Accra Central",
      "Adabraka",
      "Agbogbloshie",
      "Ambassadorial Enclave",
      "Asylum Down",
      "Chorkor",
      "East Ridge",
      "Gold Coast City",
      "High Street",
      "Jamestown",
      "Kinbu",
      "Kuku Hill",
      "Korle Bu",
      "Korle Gonno",
      "La",
      "Labone",
      "Labadi-Aborm",
      "Makola",
      "Ministries",
      "Okaishie",
      "Osu",
      "Osu-Ako Adjei",
      "Osu-Ashante",
      "Osu Kinkawe",
      "Osu-RE",
      "Rawlings Park",
      "Ridge",
      "Swalaba",
      "Tudu",
      "Ussher Town",
      "Victoriaborg",
      "West Ridge",
    ],
  },
  {
    group: "North Accra",
    places: [
      "Abeka",
      "Abelemkpe",
      "Adjiriganor",
      "Achimota",
      "Alajo",
      "Apenkwa",
      "Avenor",
      "Bawaleshie",
      "Christian Village",
      "Dzorwulu",
      "Kisseman",
      "Haatso",
      "Kaneshie",
      "Kanda",
      "Kokomlemle",
      "Kotobabi",
      "Kwashieman",
      "Lapaz",
      "Madina",
      "Maamobi",
      "Mataheko",
      "New Town",
      "Nima",
      "North Kaneshie",
      "North Ridge",
      "Nmai Djorn",
      "Pig Farm",
      "South Shiashie",
      "Roman Ridge",
      "South Tesano",
      "Tesano",
      "West Legon / Westlands",
      "Old Abelemkpe",
      "New Abelemkpe",
      "Okplongo",
    ],
  },
  {
    group: "East Accra",
    places: [
      "Airport City",
      "Airport Residential Area",
      "East Airport",
      "Baatsona",
      "Burma Camp",
      "Cantonments",
      "East Legon",
      "East Cantonments",
      "El-Wak",
      "HIPC Junction",
      "Labadi",
      "Legion Village",
      "Manet",
      "Nungua",
      "South Labadi",
      "Shiashie",
      "Spintex",
      "Teshie",
      "Tse Addo",
      "Villagio",
      "Airport Hills",
    ],
  },
  {
    group: "West Accra",
    places: [
      "Ablekuma",
      "Abossey Okai",
      "Awoshie",
      "Awudome",
      "Bubiashie",
      "Dansoman",
      "Dansoman Amanhoma",
      "Dansoman Estates",
      "Darkuman",
      "Gbegbeyise",
      "Gbawe",
      "Lartebiokorshie",
      "Mallam",
      "Mamprobi",
      "New Mamprobi",
      "Mpoase",
      "Odorkor",
      "North Odorkor",
      "Old Dansoman",
      "Official Town",
      "Odorgornor",
      "Regimanuel Estates",
      "Russia",
      "Sakaman",
      "Santa Maria",
      "Sahara",
      "Sabon Zongo",
      "Sukura",
      "Shiabu",
      "SSNIT Flats",
      "Akokorfoto",
      "Tweneboa",
      "South Odorkor",
      "First Light",
      "Zoti Area",
      "Weija",
    ],
  },
] as const;

export const accraAreas = accraAreaGroups.map(({ group, places }) => ({
  group,
  places: [...places].sort((left, right) => left.localeCompare(right, "en-GH")),
}));

export const accraAreaOtherValue = "other";
